/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/stone texturev6.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cone.geometry}
        material={materials['sabastapot canon material']}
        position={[0.234, 1.441, -0.262]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder004.geometry}
          material={materials['sabastapot canon material']}
          position={[-1.001, -0.9, 1.004]}
          rotation={[0, 0, -Math.PI / 2]}
          scale={[0.528, 0.099, 0.528]}
        />
      </mesh>
    </group>
  )
}

useGLTF.preload('/stone texturev6.glb')
