/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useState } from 'react'
import { Canvas, useFrame, useLoader } from '@react-three/fiber'
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader'
import { useGLTF } from '@react-three/drei'

export function Model({ url, scale, rotationSpeed }) {
    const gltf = useLoader(GLTFLoader, url);
    const meshRef = useRef();

    // Rotate the model every frame
    useFrame(() => {
        if (meshRef.current) {
            meshRef.current.rotation.y += rotationSpeed;
        }
    });

    return (
        <primitive
            object={gltf.scene}
            ref={meshRef}
            scale={scale}
        />
    );
}
